package com.jefferymoju.databasequizapp.database

import androidx.room.Entity
import androidx.room.PrimaryKey

//use the entity keyword that comes from the room library
// Specify the name of the table in your database
@Entity(tableName = "quiz-table")
//define the different properties/column in your data table
data class QuizEntity(
    //the id is the primary key and should be autogenerated because it should be unique
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    val name: String = "",
    val subject: String = "",
    val score: Int = 0
)
